# Generated by Django 3.1.1 on 2020-09-23 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Postid', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.TextField()),
                ('Category', models.TextField()),
                ('Description', models.TextField()),
                ('ImageId', models.ImageField(upload_to='')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('MovingService', models.BooleanField(default=False)),
                ('OrderConfirm', models.BooleanField(default=False)),
                ('Postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.post')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
